#!/bin/bash
#nitrogen --restore &
xrandr --output eDP-1 --auto --output HDMI-1-0 --auto --scale 1.5x1.5 --right-of eDP-1
#xrandr --output eDP-1 --auto --output HDMI-1-0 --auto --scale 2x2 --right-of eDP-1
#xrandr --output eDP-1 --auto --output HDMI-1-0 --auto --right-of eDP-1
